= REFLEKSJA
:author_1: Krzysztof Dolański
:author_2: Daniel Żychniewicz

=== Trochę o refleksji...

Refleksja to wszechstronny i skomplikowany mechanizm.
Jest interesująca przede wszystkim dla twórców narzędzi, mniej dla programistów aplikacji.
Jest powszechnie używana przez programy, które wymagają możliwości badania lub modyfikowania zachowania aplikacji działających na wirtualnej maszynie javy.
Jest to stosunkowo zaawansowana funkcja i powinna być używana tylko przez programistów, którzy dobrze znają podstawy języka.
Mając to na uwadze, refleksja jest potężną techniką i może umożliwić aplikacjom wykonywanie operacji, które w innym przypadku byłyby niemożliwe.

=== Jakie możliwości daje nam mechanizm refleksji:

1. Umożliwia nam analizę właściwości klasy w trakcie działania programu.
2. Pozwala na inspekcję obiektów w czasie działania programu.
3. Daje możliwość zaimplementowania generycznego kodu manipulującego tablicami.
4. Możemy wywoływać metody obiektów ????
5. Możliwość podglądania prywatnych pól jest niezbędna do prawidłowego działania debugera.
6. W celu weryfikacji np. pokrycia kodu testami machanizm refleksji pomaga przy zidentyfikowaniu api poszczególnych klas.

=== Wady

Refleksja daje nam, spore możliwości lecz nie można jej nadużywać. *Jeśli jest możliwość wykonania operacji bez pomocy refleksji, to lepiej jej unikać.*
Podczas korzystania z mechanizmu refleksji należy pamiętać o następoujących kwestiach:

. Narzut związany z wydajnością:
- Mechanizm refleksji uniemożliwia wykonywanie pewnych optymalizacji, które stosuje JVM w związku z czym refleksja jest wolniejsza i należy jej unikać w blokach kodu, które są wykonywane często.
. Kwestie dot. bezpieczeństwa:
- Refleksja działając w czasie wykonywania programu może ze względów bezpieczeństwa może nie otrzymać takiej możliwość.
Manager bezpieczeństwa może na to nie pozwolić.
. Eksponowanie stanu:
- Dostęp do pól czy metod prywatnych łamie zasady enkapsulacji/hermetyzacji a takie możliwości daje refleksja.

=== Rozkłąd jazdy

.Zaczynamy od API:
.. Klasy - pokażemy jak uzyskać objekt `Class` i przy jego pomocy dostać się do zawartości danej klasy.
.. Pola, metody, konstruktory - pokażmy jak pobierać pola, ustawiać ich wartość, wywołyuwać metody i tworzyć obiekt na podstawie określonego konstruktora.
.. Tablice i typy wyliczeniowe - pokażemy jak pobrać typ elementu tablicy oraz jak pobrać i ustawić w ww typach.

. Punktem wejścia dla wszystkich operacji refleksji jest `java.lang.Class`.
Z wyjątkiem `java.lang.reflect.ReflectPermission`, żadna z klas w `java.lang.reflect` *nie ma publicznych konstruktorów*.
Aby dostać się do tych klas, konieczne jest wywołanie odpowiednich metod na `Class`.
Istnieje kilka sposobów uzyskania obiektu `Class` w zależności od tego, czy kod ma dostęp do obiektu, nazwy klasy, typu lub istniejącego `Class`.

==== `Object.getClass()`
